@startuml

legend
Classes as follows:

----
Name
----
description
----
"functions"
====
parameters
end legend


package __init__ {
    package game {
        package Connect4 {
            class init(C4) {
                methods to be exposed to API {abstract}
                ----
                board
                players
                turn
                winner
                }
            class get_status(C4) {
                get statuses {abstract}
                ----
                active_player
                winner_check
                turn_count
                }

            class register_player(C4) {
                register player{abstract}
                ----
                player_icon
                ====
                player_UUID
                }

            class get_board(C4) {
                return current board state{abstract}
                ----
                current_board_state
                }

            class check_move(C4) {
                check move of certain player is legal: if yes: request move{abstract}
                ----
                move_legal
                ====
                column
                player
                }

            class update_status(C4) {
                update akk vakues for status atfer each succesful move {abstract}
                ----
                active_player
                active_ID
                winner
                turn_number
                }

            class detetct_win(C4) {
                detect if someone has won the game{abstract}
                ----
                }
            }
        }

    package player_local {
        package Player_Local {
            class init(PL) {
                Super_init (player)
                ====
                game
                }

            class register_game(PL) {
                }
            class is_my_tunr(PL) {}
            class get_game_status(PL) {}
            class make_move(PL) {}
            class visualise(PL) {}
            class celebrate_win(PL) {}

            }
        }
    

    package player {
        package Player {
            class init(ABS) {
                id
                icon
                board_width
                board_height
                }
            class register_in_game(ABS) {
                register player in game, assign icon {abstract}
                ----
                }
            class is_my_turn(ABS) {
                check if it is okayers turn {abstract}
                ----
                }
            class get_game_status(ABS) {
                get game status: acative player, if winner: who, turn nunmber {abstract}
                ----
                }
            class make_move(ABS) {
                prompt player to take move {abstract}
                ----
                }
            class visualise(ABS) {
                visualise current board state {abstract}
                ----
                }
            class celebrate_win(ABS) {
                visualise the win {abstract}
                ----
                }
            }
        }

    package setup {
        package Setup {
            class setup {
                installation of all required packes to Connect4 {abstract}
                ----
                name
                version
                packages
                install_requires
                python_requires
                }
            }
        }

    package coordinator {
        package Coordinator_Local {
            class init(Coord) {
            initialse Coordinator_Local with a Game and 2 players {abstract}
            ----
                }
            class play {
                handles: player registration, turn managment, winner checking {abstract}
                ----
                }
            }
        }
    }

@enduml